// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(SigedespDBContex))]
    partial class SigedespDBContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.FornecedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fornecedorid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FornecedorModelId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomefantasia");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorModelId");

                    b.ToTable("fornecedor");
                });

            modelBuilder.Entity("api.Models.InstituicaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("instituicaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSecretaria")
                        .HasColumnType("integer")
                        .HasColumnName("secretariaid");

                    b.Property<int>("IdTipoInstituicao")
                        .HasColumnType("integer")
                        .HasColumnName("tipoinstituicaoid");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("IdSecretaria");

                    b.HasIndex("IdTipoInstituicao");

                    b.ToTable("instituicao");
                });

            modelBuilder.Entity("api.Models.OrcamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orcamentoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoOrcamento")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("anoorcamento");

                    b.Property<double>("ValorOrcamento")
                        .HasMaxLength(50)
                        .HasColumnType("double precision")
                        .HasColumnName("valororcamento");

                    b.HasKey("Id");

                    b.ToTable("orcamento");
                });

            modelBuilder.Entity("api.Models.SecretariaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("secretariaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.Property<int?>("SecretariaModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("SecretariaModelId");

                    b.ToTable("secretaria");
                });

            modelBuilder.Entity("api.Models.TipoDespesaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipodespesaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SolicitaUC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("solicitauc");

                    b.Property<string>("TipoDespesa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipodespesa");

                    b.HasKey("Id");

                    b.ToTable("tipodespesa");
                });

            modelBuilder.Entity("api.Models.TipoInstituicaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipoinstituicaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoInstituicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipoinstituicao");

                    b.Property<int?>("TipoInstituicaoModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoInstituicaoModelId");

                    b.ToTable("tipoinstituicao");
                });

            modelBuilder.Entity("api.Models.TipoUsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipousuarioid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.Property<string>("PermiteLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permitelogin");

                    b.HasKey("Id");

                    b.ToTable("tipousuario");
                });

            modelBuilder.Entity("api.Models.UnidadeConsumidoraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unidadeconsumidoraid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoUC")
                        .HasColumnType("integer")
                        .HasColumnName("unidadeconsumidora");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedorid");

                    b.HasKey("Id");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("unidadeconsumidora");
                });

            modelBuilder.Entity("api.Models.UnidadeMedidaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unidademedidaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descrição");

                    b.HasKey("Id");

                    b.ToTable("unidademedida");
                });

            modelBuilder.Entity("api.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bairro");

                    b.Property<int>("CEP")
                        .HasColumnType("integer")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cidade");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpfcnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomerazaosocial");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("RgLe")
                        .HasColumnType("integer")
                        .HasColumnName("rgle");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("senha");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("api.Models.FornecedorModel", b =>
                {
                    b.HasOne("api.Models.FornecedorModel", null)
                        .WithMany("Fornecedor")
                        .HasForeignKey("FornecedorModelId");
                });

            modelBuilder.Entity("api.Models.InstituicaoModel", b =>
                {
                    b.HasOne("api.Models.SecretariaModel", "Secretaria")
                        .WithMany()
                        .HasForeignKey("IdSecretaria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.TipoInstituicaoModel", "tipoInstituicao")
                        .WithMany()
                        .HasForeignKey("IdTipoInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secretaria");

                    b.Navigation("tipoInstituicao");
                });

            modelBuilder.Entity("api.Models.SecretariaModel", b =>
                {
                    b.HasOne("api.Models.SecretariaModel", null)
                        .WithMany("Secretaria")
                        .HasForeignKey("SecretariaModelId");
                });

            modelBuilder.Entity("api.Models.TipoInstituicaoModel", b =>
                {
                    b.HasOne("api.Models.TipoInstituicaoModel", null)
                        .WithMany("TipoInstituicaoLista")
                        .HasForeignKey("TipoInstituicaoModelId");
                });

            modelBuilder.Entity("api.Models.UnidadeConsumidoraModel", b =>
                {
                    b.HasOne("api.Models.FornecedorModel", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("api.Models.FornecedorModel", b =>
                {
                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("api.Models.SecretariaModel", b =>
                {
                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("api.Models.TipoInstituicaoModel", b =>
                {
                    b.Navigation("TipoInstituicaoLista");
                });
#pragma warning restore 612, 618
        }
    }
}
