services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DBSigedesp
    ports:
      - "5432:5432" # Porta exposta para o banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume persistente para dados do PostgreSQL
      - ../database/DBSigedesp.sql:/docker-entrypoint-initdb.d/DBSigedesp.sql # Carrega o banco de dados inicial
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ../api # Diretório onde está seu Dockerfile da API
    container_name: api_container
    restart: always
    ports:
      - "7274:8080" # Mapeia a porta 5000 do contêiner para a porta 7096 da máquina
    depends_on:
      postgres:
        condition: service_healthy # Garante que o postgres esteja pronto antes de iniciar a API
    environment:
      DATABASE_URL: "Host=postgres_container;Port=5432;Database=DBSigedesp;Username=postgres;Password=123456;"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local # Volume local para persistência dos dados