--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Despesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Despesa" (
    despesaid integer NOT NULL,
    numerodocumento character varying(50) NOT NULL,
    numerocontrole character varying(50) NOT NULL,
    anomesconsumo character varying(50) NOT NULL,
    quantidadeconsumida numeric(18,2) NOT NULL,
    datavencimento date NOT NULL,
    valorprevisto numeric(18,2) NOT NULL,
    datapagamento date NOT NULL,
    valorpago numeric(18,2) NOT NULL,
    anoemissao integer NOT NULL,
    semestreemissao integer NOT NULL,
    trimestreemissao integer NOT NULL,
    mesemissao integer NOT NULL,
    situacao integer NOT NULL,
    "FornecedorId" integer,
    fornecedorid integer NOT NULL,
    "UnidadeConsumidoraId" integer,
    unidadeconsumidoraid integer NOT NULL,
    "InstituicaoId" integer,
    instituicaoid integer NOT NULL,
    "OrcamentoId" integer,
    orcamentoid integer NOT NULL,
    "TipoDespesaId" integer,
    tipodespesaid integer NOT NULL,
    statusdespesa integer NOT NULL,
    "UsuarioId" integer,
    usuarioid integer NOT NULL
);


ALTER TABLE public."Despesa" OWNER TO postgres;

--
-- Name: Despesa_despesaid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Despesa" ALTER COLUMN despesaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Despesa_despesaid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: fornecedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fornecedor (
    fornecedorid integer NOT NULL,
    nomefantasia character varying(100) NOT NULL,
    situacao integer NOT NULL,
    cnpj character varying(14) NOT NULL,
    nome character varying(100) NOT NULL,
    logradouro character varying(100) NOT NULL,
    numero character varying(15) NOT NULL,
    bairro character varying(100) NOT NULL,
    cep character varying(8) NOT NULL,
    telefone character varying(11) NOT NULL,
    email character varying(100) NOT NULL,
    cidade character varying(25) NOT NULL,
    estado character varying(25) NOT NULL
);


ALTER TABLE public.fornecedor OWNER TO postgres;

--
-- Name: fornecedor_fornecedorid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fornecedor ALTER COLUMN fornecedorid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedor_fornecedorid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instituicao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.instituicao (
    instituicaoid integer NOT NULL,
    situacao integer NOT NULL,
    cnpj character varying(14) NOT NULL,
    nome character varying(100) NOT NULL,
    logradouro character varying(100) NOT NULL,
    numero character varying(15) NOT NULL,
    bairro character varying(100) NOT NULL,
    cep character varying(8) NOT NULL,
    nomerazaosocial character varying(100) NOT NULL,
    telefone character varying(11) NOT NULL,
    email character varying(100) NOT NULL,
    cidade character varying(25) NOT NULL,
    estado character varying(25) NOT NULL,
    tipoinstituicaoid integer NOT NULL,
    secretariaid integer NOT NULL,
    "SecretariaModelId" integer,
    "TipoInstituicaoModelId" integer
);


ALTER TABLE public.instituicao OWNER TO postgres;

--
-- Name: instituicao_instituicaoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.instituicao ALTER COLUMN instituicaoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instituicao_instituicaoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orcamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orcamento (
    orcamentoid integer NOT NULL,
    anoorcamento integer NOT NULL,
    valororcamento double precision NOT NULL,
    tipodespesaid integer NOT NULL,
    instituicaoid integer NOT NULL,
    "InstituicaoModelId" integer,
    "TipoDespesaModelId" integer
);


ALTER TABLE public.orcamento OWNER TO postgres;

--
-- Name: orcamento_orcamentoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orcamento ALTER COLUMN orcamentoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orcamento_orcamentoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secretaria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.secretaria (
    secretariaid integer NOT NULL,
    situacao integer NOT NULL,
    descricao character varying(100) NOT NULL,
    cnpj character varying(14) NOT NULL,
    nome character varying(100) NOT NULL,
    logradouro character varying(100) NOT NULL,
    numero character varying(15) NOT NULL,
    bairro character varying(100) NOT NULL,
    cep character varying(8) NOT NULL,
    nomerazaosocial character varying(100) NOT NULL,
    telefone character varying(11) NOT NULL,
    email character varying(100) NOT NULL,
    cidade character varying(25) NOT NULL,
    estado character varying(25) NOT NULL
);


ALTER TABLE public.secretaria OWNER TO postgres;

--
-- Name: secretaria_secretariaid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.secretaria ALTER COLUMN secretariaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secretaria_secretariaid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipodespesa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipodespesa (
    tipodespesaid integer NOT NULL,
    descricao character varying(50) NOT NULL,
    solicitauc integer NOT NULL,
    idunidademedida integer NOT NULL,
    "UnidadeMedidaModelId" integer
);


ALTER TABLE public.tipodespesa OWNER TO postgres;

--
-- Name: tipodespesa_tipodespesaid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipodespesa ALTER COLUMN tipodespesaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipodespesa_tipodespesaid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipoinstituicao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipoinstituicao (
    tipoinstituicaoid integer NOT NULL,
    descricao character varying(100) NOT NULL,
    nome character varying(100) NOT NULL
);


ALTER TABLE public.tipoinstituicao OWNER TO postgres;

--
-- Name: tipoinstituicao_tipoinstituicaoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipoinstituicao ALTER COLUMN tipoinstituicaoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipoinstituicao_tipoinstituicaoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidadeconsumidora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unidadeconsumidora (
    unidadeconsumidoraid integer NOT NULL,
    unidadeconsumidora character varying(10) NOT NULL,
    fornecedorid integer NOT NULL,
    instituicaoid integer NOT NULL,
    "FornecedorModelId" integer,
    "InstituicaoModelId" integer
);


ALTER TABLE public.unidadeconsumidora OWNER TO postgres;

--
-- Name: unidadeconsumidora_unidadeconsumidoraid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.unidadeconsumidora ALTER COLUMN unidadeconsumidoraid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidadeconsumidora_unidadeconsumidoraid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidademedida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unidademedida (
    unidademedidaid integer NOT NULL,
    "descrição" character varying(100) NOT NULL,
    abreviatura character varying(10) NOT NULL
);


ALTER TABLE public.unidademedida OWNER TO postgres;

--
-- Name: unidademedida_unidademedidaid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.unidademedida ALTER COLUMN unidademedidaid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidademedida_unidademedidaid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    usuarioid integer NOT NULL,
    cpf character varying(11) NOT NULL,
    rg character varying(12) NOT NULL,
    nome character varying(100) NOT NULL,
    logradouro character varying(100) NOT NULL,
    numero character varying(15) NOT NULL,
    cidade character varying(25) NOT NULL,
    estado character varying(25) NOT NULL,
    cep character varying(8) NOT NULL,
    email character varying(100) NOT NULL,
    senha character varying(15) NOT NULL,
    situacao integer NOT NULL,
    matricula character varying(100) NOT NULL,
    tipousuario integer NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_usuarioid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN usuarioid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_usuarioid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Despesa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Despesa" (despesaid, numerodocumento, numerocontrole, anomesconsumo, quantidadeconsumida, datavencimento, valorprevisto, datapagamento, valorpago, anoemissao, semestreemissao, trimestreemissao, mesemissao, situacao, "FornecedorId", fornecedorid, "UnidadeConsumidoraId", unidadeconsumidoraid, "InstituicaoId", instituicaoid, "OrcamentoId", orcamentoid, "TipoDespesaId", tipodespesaid, statusdespesa, "UsuarioId", usuarioid) FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240913162541_CriarBanco	8.0.6
\.


--
-- Data for Name: fornecedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fornecedor (fornecedorid, nomefantasia, situacao, cnpj, nome, logradouro, numero, bairro, cep, telefone, email, cidade, estado) FROM stdin;
\.


--
-- Data for Name: instituicao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.instituicao (instituicaoid, situacao, cnpj, nome, logradouro, numero, bairro, cep, nomerazaosocial, telefone, email, cidade, estado, tipoinstituicaoid, secretariaid, "SecretariaModelId", "TipoInstituicaoModelId") FROM stdin;
\.


--
-- Data for Name: orcamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orcamento (orcamentoid, anoorcamento, valororcamento, tipodespesaid, instituicaoid, "InstituicaoModelId", "TipoDespesaModelId") FROM stdin;
\.


--
-- Data for Name: secretaria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.secretaria (secretariaid, situacao, descricao, cnpj, nome, logradouro, numero, bairro, cep, nomerazaosocial, telefone, email, cidade, estado) FROM stdin;
\.


--
-- Data for Name: tipodespesa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipodespesa (tipodespesaid, descricao, solicitauc, idunidademedida, "UnidadeMedidaModelId") FROM stdin;
\.


--
-- Data for Name: tipoinstituicao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipoinstituicao (tipoinstituicaoid, descricao, nome) FROM stdin;
\.


--
-- Data for Name: unidadeconsumidora; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.unidadeconsumidora (unidadeconsumidoraid, unidadeconsumidora, fornecedorid, instituicaoid, "FornecedorModelId", "InstituicaoModelId") FROM stdin;
\.


--
-- Data for Name: unidademedida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.unidademedida (unidademedidaid, "descrição", abreviatura) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (usuarioid, cpf, rg, nome, logradouro, numero, cidade, estado, cep, email, senha, situacao, matricula, tipousuario) FROM stdin;
\.


--
-- Name: Despesa_despesaid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Despesa_despesaid_seq"', 1, false);


--
-- Name: fornecedor_fornecedorid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fornecedor_fornecedorid_seq', 1, false);


--
-- Name: instituicao_instituicaoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.instituicao_instituicaoid_seq', 1, false);


--
-- Name: orcamento_orcamentoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orcamento_orcamentoid_seq', 1, false);


--
-- Name: secretaria_secretariaid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.secretaria_secretariaid_seq', 1, false);


--
-- Name: tipodespesa_tipodespesaid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipodespesa_tipodespesaid_seq', 1, false);


--
-- Name: tipoinstituicao_tipoinstituicaoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipoinstituicao_tipoinstituicaoid_seq', 1, false);


--
-- Name: unidadeconsumidora_unidadeconsumidoraid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.unidadeconsumidora_unidadeconsumidoraid_seq', 1, false);


--
-- Name: unidademedida_unidademedidaid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.unidademedida_unidademedidaid_seq', 1, false);


--
-- Name: usuario_usuarioid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_usuarioid_seq', 1, false);


--
-- Name: Despesa PK_Despesa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "PK_Despesa" PRIMARY KEY (despesaid);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: fornecedor PK_fornecedor; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT "PK_fornecedor" PRIMARY KEY (fornecedorid);


--
-- Name: instituicao PK_instituicao; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instituicao
    ADD CONSTRAINT "PK_instituicao" PRIMARY KEY (instituicaoid);


--
-- Name: orcamento PK_orcamento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT "PK_orcamento" PRIMARY KEY (orcamentoid);


--
-- Name: secretaria PK_secretaria; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.secretaria
    ADD CONSTRAINT "PK_secretaria" PRIMARY KEY (secretariaid);


--
-- Name: tipodespesa PK_tipodespesa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipodespesa
    ADD CONSTRAINT "PK_tipodespesa" PRIMARY KEY (tipodespesaid);


--
-- Name: tipoinstituicao PK_tipoinstituicao; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipoinstituicao
    ADD CONSTRAINT "PK_tipoinstituicao" PRIMARY KEY (tipoinstituicaoid);


--
-- Name: unidadeconsumidora PK_unidadeconsumidora; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidadeconsumidora
    ADD CONSTRAINT "PK_unidadeconsumidora" PRIMARY KEY (unidadeconsumidoraid);


--
-- Name: unidademedida PK_unidademedida; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidademedida
    ADD CONSTRAINT "PK_unidademedida" PRIMARY KEY (unidademedidaid);


--
-- Name: usuario PK_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "PK_usuario" PRIMARY KEY (usuarioid);


--
-- Name: IX_Despesa_FornecedorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_FornecedorId" ON public."Despesa" USING btree ("FornecedorId");


--
-- Name: IX_Despesa_InstituicaoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_InstituicaoId" ON public."Despesa" USING btree ("InstituicaoId");


--
-- Name: IX_Despesa_OrcamentoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_OrcamentoId" ON public."Despesa" USING btree ("OrcamentoId");


--
-- Name: IX_Despesa_TipoDespesaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_TipoDespesaId" ON public."Despesa" USING btree ("TipoDespesaId");


--
-- Name: IX_Despesa_UnidadeConsumidoraId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_UnidadeConsumidoraId" ON public."Despesa" USING btree ("UnidadeConsumidoraId");


--
-- Name: IX_Despesa_UsuarioId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Despesa_UsuarioId" ON public."Despesa" USING btree ("UsuarioId");


--
-- Name: IX_instituicao_SecretariaModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_instituicao_SecretariaModelId" ON public.instituicao USING btree ("SecretariaModelId");


--
-- Name: IX_instituicao_TipoInstituicaoModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_instituicao_TipoInstituicaoModelId" ON public.instituicao USING btree ("TipoInstituicaoModelId");


--
-- Name: IX_instituicao_secretariaid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_instituicao_secretariaid" ON public.instituicao USING btree (secretariaid);


--
-- Name: IX_instituicao_tipoinstituicaoid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_instituicao_tipoinstituicaoid" ON public.instituicao USING btree (tipoinstituicaoid);


--
-- Name: IX_orcamento_InstituicaoModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orcamento_InstituicaoModelId" ON public.orcamento USING btree ("InstituicaoModelId");


--
-- Name: IX_orcamento_TipoDespesaModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orcamento_TipoDespesaModelId" ON public.orcamento USING btree ("TipoDespesaModelId");


--
-- Name: IX_orcamento_instituicaoid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orcamento_instituicaoid" ON public.orcamento USING btree (instituicaoid);


--
-- Name: IX_orcamento_tipodespesaid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orcamento_tipodespesaid" ON public.orcamento USING btree (tipodespesaid);


--
-- Name: IX_tipodespesa_UnidadeMedidaModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tipodespesa_UnidadeMedidaModelId" ON public.tipodespesa USING btree ("UnidadeMedidaModelId");


--
-- Name: IX_tipodespesa_idunidademedida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tipodespesa_idunidademedida" ON public.tipodespesa USING btree (idunidademedida);


--
-- Name: IX_unidadeconsumidora_FornecedorModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_unidadeconsumidora_FornecedorModelId" ON public.unidadeconsumidora USING btree ("FornecedorModelId");


--
-- Name: IX_unidadeconsumidora_InstituicaoModelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_unidadeconsumidora_InstituicaoModelId" ON public.unidadeconsumidora USING btree ("InstituicaoModelId");


--
-- Name: IX_unidadeconsumidora_fornecedorid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_unidadeconsumidora_fornecedorid" ON public.unidadeconsumidora USING btree (fornecedorid);


--
-- Name: IX_unidadeconsumidora_instituicaoid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_unidadeconsumidora_instituicaoid" ON public.unidadeconsumidora USING btree (instituicaoid);


--
-- Name: Despesa FK_Despesa_fornecedor_FornecedorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_fornecedor_FornecedorId" FOREIGN KEY ("FornecedorId") REFERENCES public.fornecedor(fornecedorid);


--
-- Name: Despesa FK_Despesa_instituicao_InstituicaoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_instituicao_InstituicaoId" FOREIGN KEY ("InstituicaoId") REFERENCES public.instituicao(instituicaoid);


--
-- Name: Despesa FK_Despesa_orcamento_OrcamentoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_orcamento_OrcamentoId" FOREIGN KEY ("OrcamentoId") REFERENCES public.orcamento(orcamentoid);


--
-- Name: Despesa FK_Despesa_tipodespesa_TipoDespesaId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_tipodespesa_TipoDespesaId" FOREIGN KEY ("TipoDespesaId") REFERENCES public.tipodespesa(tipodespesaid);


--
-- Name: Despesa FK_Despesa_unidadeconsumidora_UnidadeConsumidoraId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_unidadeconsumidora_UnidadeConsumidoraId" FOREIGN KEY ("UnidadeConsumidoraId") REFERENCES public.unidadeconsumidora(unidadeconsumidoraid);


--
-- Name: Despesa FK_Despesa_usuario_UsuarioId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Despesa"
    ADD CONSTRAINT "FK_Despesa_usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES public.usuario(usuarioid);


--
-- Name: instituicao FK_instituicao_secretaria_SecretariaModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instituicao
    ADD CONSTRAINT "FK_instituicao_secretaria_SecretariaModelId" FOREIGN KEY ("SecretariaModelId") REFERENCES public.secretaria(secretariaid);


--
-- Name: instituicao FK_instituicao_secretaria_secretariaid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instituicao
    ADD CONSTRAINT "FK_instituicao_secretaria_secretariaid" FOREIGN KEY (secretariaid) REFERENCES public.secretaria(secretariaid) ON DELETE CASCADE;


--
-- Name: instituicao FK_instituicao_tipoinstituicao_TipoInstituicaoModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instituicao
    ADD CONSTRAINT "FK_instituicao_tipoinstituicao_TipoInstituicaoModelId" FOREIGN KEY ("TipoInstituicaoModelId") REFERENCES public.tipoinstituicao(tipoinstituicaoid);


--
-- Name: instituicao FK_instituicao_tipoinstituicao_tipoinstituicaoid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instituicao
    ADD CONSTRAINT "FK_instituicao_tipoinstituicao_tipoinstituicaoid" FOREIGN KEY (tipoinstituicaoid) REFERENCES public.tipoinstituicao(tipoinstituicaoid) ON DELETE CASCADE;


--
-- Name: orcamento FK_orcamento_instituicao_InstituicaoModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT "FK_orcamento_instituicao_InstituicaoModelId" FOREIGN KEY ("InstituicaoModelId") REFERENCES public.instituicao(instituicaoid);


--
-- Name: orcamento FK_orcamento_instituicao_instituicaoid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT "FK_orcamento_instituicao_instituicaoid" FOREIGN KEY (instituicaoid) REFERENCES public.instituicao(instituicaoid) ON DELETE CASCADE;


--
-- Name: orcamento FK_orcamento_tipodespesa_TipoDespesaModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT "FK_orcamento_tipodespesa_TipoDespesaModelId" FOREIGN KEY ("TipoDespesaModelId") REFERENCES public.tipodespesa(tipodespesaid);


--
-- Name: orcamento FK_orcamento_tipodespesa_tipodespesaid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orcamento
    ADD CONSTRAINT "FK_orcamento_tipodespesa_tipodespesaid" FOREIGN KEY (tipodespesaid) REFERENCES public.tipodespesa(tipodespesaid) ON DELETE CASCADE;


--
-- Name: tipodespesa FK_tipodespesa_unidademedida_UnidadeMedidaModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipodespesa
    ADD CONSTRAINT "FK_tipodespesa_unidademedida_UnidadeMedidaModelId" FOREIGN KEY ("UnidadeMedidaModelId") REFERENCES public.unidademedida(unidademedidaid);


--
-- Name: tipodespesa FK_tipodespesa_unidademedida_idunidademedida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipodespesa
    ADD CONSTRAINT "FK_tipodespesa_unidademedida_idunidademedida" FOREIGN KEY (idunidademedida) REFERENCES public.unidademedida(unidademedidaid) ON DELETE CASCADE;


--
-- Name: unidadeconsumidora FK_unidadeconsumidora_fornecedor_FornecedorModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidadeconsumidora
    ADD CONSTRAINT "FK_unidadeconsumidora_fornecedor_FornecedorModelId" FOREIGN KEY ("FornecedorModelId") REFERENCES public.fornecedor(fornecedorid);


--
-- Name: unidadeconsumidora FK_unidadeconsumidora_fornecedor_fornecedorid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidadeconsumidora
    ADD CONSTRAINT "FK_unidadeconsumidora_fornecedor_fornecedorid" FOREIGN KEY (fornecedorid) REFERENCES public.fornecedor(fornecedorid) ON DELETE CASCADE;


--
-- Name: unidadeconsumidora FK_unidadeconsumidora_instituicao_InstituicaoModelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidadeconsumidora
    ADD CONSTRAINT "FK_unidadeconsumidora_instituicao_InstituicaoModelId" FOREIGN KEY ("InstituicaoModelId") REFERENCES public.instituicao(instituicaoid);


--
-- Name: unidadeconsumidora FK_unidadeconsumidora_instituicao_instituicaoid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidadeconsumidora
    ADD CONSTRAINT "FK_unidadeconsumidora_instituicao_instituicaoid" FOREIGN KEY (instituicaoid) REFERENCES public.instituicao(instituicaoid) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

